package com.bansalcoders.monityx.domain.model

/**
 * An actionable recommendation to reduce spending on a specific subscription.
 * Generated by [GetSavingsSuggestionsUseCase].
 *
 * All monetary amounts are expressed in the user's [baseCurrency].
 */
data class SavingsSuggestion(
    val subscription: Subscription,
    val reason: SuggestionReason,
    val monthlySavings: Double,  // in base currency
    val yearlySavings: Double,   // in base currency
)

enum class SuggestionReason(val title: String, val actionHint: String) {
    INACTIVE(
        title      = "Inactive subscription",
        actionHint = "Cancel this to stop paying immediately",
    ),
    DUPLICATE_CATEGORY(
        title      = "Duplicate service",
        actionHint = "You have a cheaper alternative in the same category",
    ),
    SWITCH_TO_YEARLY(
        title      = "Switch to annual billing",
        actionHint = "Paying yearly typically saves ~15%",
    ),
    LIKELY_UNUSED(
        title      = "Possibly unused",
        actionHint = "Yearly subscription with no recent activity signals",
    ),
}
